### ISSUE TITLE
Future POSIX HTTP Client improvements

### ISSUE THREAD

**Issue by deathbaba** [C5T/Current#12] opened 2014-12-10 03:22 UTC
- Connect and Read timeouts support
- If the hostname resolves to multiple IP addresses, client can try each in RFC 3484 order. If connecting to each of these addresses fails, multiple timeouts will elapse before the connect attempt throws an exception. Host names that support both IPv6 and IPv4 always have at least 2 IP addresses.

**Comment by dkorolev** [comment] 2016-08-28 04:10
The issue is not forgotten, but it's safe to assume we won't touch it until hitting it for real in prod.

Plausible workaround: nginx-proxy a remove server through a port on localhost. We do it for HTTPS, a more important feature of the HTTP client, which we consciously don't support and don't plan to any time soon.

**Comment by dkorolev** [comment] 2016-08-28 04:10
(And I'll close it because OCD.)

**Closed by dkorolev** 2016-08-28 04:10 UTC
